language: java
script:
  - mvn clean test
jobs:
  include:
    - stage: deploy
      install: skip
      script: skip
      deploy: &heroku
        provider: heroku
        api_key: 02fa123e-3206-47cf-bcfd-aa7bb61859a3
        app: justmove-app